### ISSUE TITLE
Any way to get evaluator.dll ?

### ISSUE THREAD

**Issue by kidd** [meatich/NEAT#1]
Hi, 
I'm trying to study the code in here, and I see there's a file 'evaluator.dll' referenced but not in the repo, and I'm not sure I can find it in the net.

Could you provide it in the repo? or a link to a repo to build it?  

Thanks!!

**Comment by some-mthfka** [comment]
Hello,

evaluator.dll is a general shared library that provides a C interface for a fitness function. So, basically it's for when you want to write a fitness function in C/C++. If the fitness function is in Lisp, no need to worry about either evaluator.dll or pln-experiment.lisp that uses it.
Anyway, if you are willing to try, an example evaluator.dll can be compiled using this simulation https://github.com/meatich/PLN-Simulation
But no need to compile if you use Windows, I just pre-released:
https://github.com/meatich/PLN-Simulation/releases/tag/0.7
from which you can get
https://github.com/meatich/PLN-Simulation/releases/download/0.7/demo.zip
which contains evaluator.dll

:)

**Comment by kidd** [comment]
thanks for the info and links!
